package com.sebas.booksapp.ui.theme

import androidx.compose.ui.graphics.Color

val primaryDark = Color(0xFF8FCEF3)
val onPrimaryDark = Color(0xFF003549)
val primaryContainerDark = Color(0xFF004C68)
val onPrimaryContainerDark = Color(0xFFC3E8FF)
val secondaryDark = Color(0xFFA2D399)
val onSecondaryDark = Color(0xFF0C390E)
val secondaryContainerDark = Color(0xFF255023)
val onSecondaryContainerDark = Color(0xFFBDF0B3)
val tertiaryDark = Color(0xFFFFB77B)
val onTertiaryDark = Color(0xFF4D2700)
val tertiaryContainerDark = Color(0xFF6C3A05)
val onTertiaryContainerDark = Color(0xFFFFDCC2)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1417)
val onBackgroundDark = Color(0xFFDFE3E7)
val surfaceDark = Color(0xFF111318)
val onSurfaceDark = Color(0xFFE1E2E9)
val surfaceVariantDark = Color(0xFF42474E)
val onSurfaceVariantDark = Color(0xFFC2C7CE)
val outlineDark = Color(0xFF8C9198)
val outlineVariantDark = Color(0xFF42474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E2E9)
val inverseOnSurfaceDark = Color(0xFF2E3035)
val inversePrimaryDark = Color(0xFF1B6585)
val surfaceDimDark = Color(0xFF111318)
val surfaceBrightDark = Color(0xFF37393E)
val surfaceContainerLowestDark = Color(0xFF0C0E13)
val surfaceContainerLowDark = Color(0xFF191C20)
val surfaceContainerDark = Color(0xFF1D2024)
val surfaceContainerHighDark = Color(0xFF272A2F)
val surfaceContainerHighestDark = Color(0xFF32353A)

val primaryDarkMediumContrast = Color(0xFF3FBCF4)
val onPrimaryDarkMediumContrast = Color(0xFF001925)
val primaryContainerDarkMediumContrast = Color(0xFF5898BB)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFF00C02F)
val onSecondaryDarkMediumContrast = Color(0xFF001C02)
val secondaryContainerDarkMediumContrast = Color(0xFF6E9C67)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFF9010)
val onTertiaryDarkMediumContrast = Color(0xFF271100)
val tertiaryContainerDarkMediumContrast = Color(0xFFC3824A)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0F1417)
val onBackgroundDarkMediumContrast = Color(0xFFDFE3E7)
val surfaceDarkMediumContrast = Color(0xFF445565)
val onSurfaceDarkMediumContrast = Color(0xFFFBFAFF)
val surfaceVariantDarkMediumContrast = Color(0xFF42474E)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC6CBD3)
val outlineDarkMediumContrast = Color(0xFF9EA3AB)
val outlineVariantDarkMediumContrast = Color(0xFF7E848B)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE1E2E9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF272A2F)
val inversePrimaryDarkMediumContrast = Color(0xFF004E6A)

val primaryDarkHighContrast = Color(0xFFF8FBFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF93D3F7)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFF1FFE9)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFA6D89D)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFFAF8)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFBD87)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF0F1417)
val onBackgroundDarkHighContrast = Color(0xFFDFE3E7)
val surfaceDarkHighContrast = Color(0xFF111318)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF42474E)
val onSurfaceVariantDarkHighContrast = Color(0xFFF9FBFF)
val outlineDarkHighContrast = Color(0xFFC6CBD3)
val outlineVariantDarkHighContrast = Color(0xFFC6CBD3)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE1E2E9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF002E40)
val surfaceDimDarkHighContrast = Color(0xFF111318)
val surfaceBrightDarkHighContrast = Color(0xFF37393E)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0C0E13)
val surfaceContainerLowDarkHighContrast = Color(0xFF191C20)
val surfaceContainerDarkHighContrast = Color(0xFF1D2024)
val surfaceContainerHighDarkHighContrast = Color(0xFF272A2F)
val surfaceContainerHighestDarkHighContrast = Color(0xFF32353A)








